### ISSUE TITLE
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

### ISSUE THREAD

**Issue by divya-rakheja** [MPI-IS/mesh#105]
Has anyone come across this issue and resolved it while running bash visualise.sh

Traceback (most recent call last):
  File "/home/cvlab/Desktop/Divya_Excecutive/TalkSHOW/scripts/diversity.py", line 352, in <module>
    main()
  File "/home/cvlab/Desktop/Divya_Excecutive/TalkSHOW/scripts/diversity.py", line 347, in main
    infer(config.Data.data_root, generator, generator_face, generator2, args.exp_name, infer_loader, infer_set, device,
  File "/home/cvlab/Desktop/Divya_Excecutive/TalkSHOW/scripts/diversity.py", line 294, in infer
    rendertool._render_sequences(cur_wav_file, vertices_list[1:], stand=stand, face=face)
  File "/home/cvlab/Desktop/Divya_Excecutive/TalkSHOW/visualise/rendering.py", line 129, in _render_sequences
    self._render_sequences_helper(video_fname, cur_wav_file, v_list, stand, face, whole_body, transcript)
  File "/home/cvlab/Desktop/Divya_Excecutive/TalkSHOW/visualise/rendering.py", line 179, in _render_sequences_helper
    r = pyrender.OffscreenRenderer(viewport_width=800, viewport_height=viewport_height)
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 170, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyglet/window/__init__.py", line 591, in __init__
    display = pyglet.canvas.get_display()
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/cvlab/miniconda3/envs/talkshow/lib/python3.10/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

**Comment by chuxiang93** [comment]
same question.
