### ISSUE TITLE
shutil.Error: [('/usr/include/python2.7/numpy'

### ISSUE THREAD

**Issue by xamxixixo** [MPI-IS/mesh#16]
Hello, I'm trying to install mesh on Google Colab. I have installed boost, virtualenv. When I did the make, this error occured:

```
********
********
******** mesh_package : Building the virtualenv for installation
********
********

Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1156, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1473, in install_python
    copy_include_dir(standard_lib_include_dir, inc_dir, symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1383, in copy_include_dir
    copyfile(include_src, include_dest, symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 423, in copyfile
    copy_file_or_folder(src, dest, symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 401, in copy_file_or_folder
    shutil.copytree(src, dest, symlink)
  File "/usr/lib/python2.7/shutil.py", line 222, in copytree
    raise Error, errors
shutil.Error: [('/usr/include/python2.7/numpy', '/content/drive/My Drive/AI_COLLAB/mesh/temporary_test/venv/include/python2.7/numpy', '[Errno 38] Function not implemented')]
Makefile:48: recipe for target 'temporary_test/package_creation' failed
make: *** [temporary_test/package_creation] Error 1
```

Can you please help?

Thank you.

**Comment by jcpassy** [comment]
Hi @xamxixixo ,

Python 2.7 is not supported anymore. Please use Python 3.5.
Cheers!
