### ISSUE TITLE
make all vs sudo make all 

### ISSUE THREAD

**Issue by cravisjan97** [MPI-IS/mesh#41]
I have created a python 3 virtual environment and I am trying to install MPI-IS mesh processing library. 

When I try running the command "make all", I get the following error:

```
\033[0;36m----- [ mesh_package ] Installing with the interpreter /home/csundaram/my_venv/bin/python (version 3.6.9)\033[0m
Collecting setuptools (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/95/95/f657b6e17f00c3f35b5f68b10e46c3a43af353d8856bd57bfcfb1dbb3e92/setuptools-47.1.1-py3-none-any.whl
Collecting numpy (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/03/27/e35e7c6e6a52fab9fcc64fc2b20c6b516eba930bb02b10ace3b38200d3ab/numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting matplotlib (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/93/4b/52da6b1523d5139d04e02d9e26ceda6146b48f2a4e5d2abfdf1c7bac8c40/matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyopengl (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/47/9a/8d9364533ebcaa13621994a63dcc6a6051e27671ae5e1715dac4af18cac2/PyOpenGL-3.1.5-py3-none-any.whl
Collecting pillow (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e0/50/8e78e6f62ffa50d6ca95c281d5a2819bef66d023ac1b723e253de5bda9c5/Pillow-7.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyzmq (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyyaml (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Collecting opencv-python (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/72/c2/e9cf54ae5b1102020ef895866a67cb2e1aef72f16dd1fde5b5fb1495ad9c/opencv_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ae/23/147de658aabbf968324551ea22c0c13a00284c4ef49a77002e91f79657b7/kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... error
  Complete output from command /home/csundaram/my_venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-93g47k8k/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmplsxaupo8pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
Failed to build pyyaml
Installing collected packages: setuptools, numpy, six, python-dateutil, pyparsing, kiwisolver, cycler, matplotlib, scipy, pyopengl, pillow, pyzmq, pyyaml, opencv-python
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/home/csundaram/my_venv/bin/easy_install' -> '/tmp/pip-hq3d0sq8-uninstall/home/csundaram/my_venv/bin/easy_install'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/csundaram/my_venv/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.6/shutil.py", line 565, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/home/csundaram/my_venv/bin/easy_install'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2
```

But when I run sudo make all, the installation works but I think it installs on the Python 2.7 version. After I finish my installation, when I run "make tests", I get the following error:
```
ModuleNotFoundError: No module named 'psbody'
```

Any help regarding the installation is appreciated. Thanks in advance

**Comment by zqq-judy** [comment]
Hello, have you solved this problem? I also got this error when I was running ‘’ make tests ‘’. 
`ModuleNotFoundError: No module named 'psbody'`

Can you share your solution?

**Comment by jcpassy** [comment]
Hi @cravisjan97,
The `ModueleNotFoundError` is caused by the fact that the installation step failed.
The problem seems to be with your virtual environment. Is it possible that you created your virtual environment with sudo?
Can you give me a bit more details, especially:
* python version
* pip version
* the exact commands your ran, including these for creating the virtual environment.

Thanks!
