### ISSUE TITLE
 Platform does not define a GLUT font retrieval function

### ISSUE THREAD

**Issue by ZZWENG** [MPI-IS/mesh#49]
I followed the readme to build this repo. When I do `make tests`, I got this error. Have you by any chance know this error?

pyopengl 3.1.5
ubuntu16

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/users/zzweng/venv2/lib/python3.6/site-packages/psbody_mesh-0.4-py3.6-linux-x86_64.egg/psbody/mesh/__init__.py", line 10, in <module>
    from .meshviewer import MeshViewer, MeshViewers
  File "/scratch/users/zzweng/venv2/lib/python3.6/site-packages/psbody_mesh-0.4-py3.6-linux-x86_64.egg/psbody/mesh/meshviewer.py", line 49, in <module>
    from OpenGL import GL, GLU, GLUT
  File "/scratch/users/zzweng/venv2/lib/python3.6/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
    from OpenGL.GLUT.fonts import *
  File "/scratch/users/zzweng/venv2/lib/python3.6/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
    p = platform.getGLUTFontPointer( name )
  File "/scratch/users/zzweng/venv2/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 345, in getGLUTFontPointer
    """Platform does not define a GLUT font retrieval function"""
NotImplementedError: Platform does not define a GLUT font retrieval function
make: *** [import_tests] Error 1
```

**Comment by ZZWENG** [comment]
Resolved.

**Comment by GrigorySamokhin** [comment]
@ZZWENG How do you resolved it?

**Comment by ZZWENG** [comment]
> @ZZWENG How do you resolved it?


I did `export PYOPENGL_PLATFORM=osmesa`, and also added -X when I ssh'ed into the linux machine.

**Comment by fyviezhao** [comment]
> > @ZZWENG How do you resolved it?
> 
> I did `export PYOPENGL_PLATFORM=osmesa`, and also added -X when I ssh'ed into the linux machine.

This doesn't work for me. Still raise the same error:
```shell
Traceback (most recent call last):
  File "run_tailornet.py", line 6, in <module>
    from psbody.mesh import Mesh
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/psbody/mesh/__init__.py", line 10, in <module>
    from .meshviewer import MeshViewer, MeshViewers
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/psbody/mesh/meshviewer.py", line 49, in <module>
    from OpenGL import GL, GLU, GLUT
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
    from OpenGL.GLUT.fonts import *
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
    p = platform.getGLUTFontPointer( name )
  File "/data/miniconda3/envs/pytorch/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 344, in getGLUTFontPointer
    raise NotImplementedError(
NotImplementedError: Platform does not define a GLUT font retrieval function
```
Can someone help me with this error?
