### ISSUE TITLE
Mesh with Manjaro 20.2

### ISSUE THREAD

**Issue by brandreea** [MPI-IS/mesh#53]
Hi!

I am trying to install the Mesh library in Linux Manjaro 20.2, but I keep getting the following error when running the `make all `command:
```
/home/brandeea/anaconda3/envs/voca/compiler_compat/ld: build/temp.linux-x86_64-3.6/mesh/src/aabb_normals.o: unable to initialize decompress status for section .debug_info
    /home/brandeea/anaconda3/envs/voca/compiler_compat/ld: build/temp.linux-x86_64-3.6/mesh/src/aabb_normals.o: unable to initialize decompress status for section .debug_info
    /home/brandeea/anaconda3/envs/voca/compiler_compat/ld: build/temp.linux-x86_64-3.6/mesh/src/aabb_normals.o: unable to initialize decompress status for section .debug_info
    /home/brandeea/anaconda3/envs/voca/compiler_compat/ld: build/temp.linux-x86_64-3.6/mesh/src/aabb_normals.o: unable to initialize decompress status for section .debug_info
    build/temp.linux-x86_64-3.6/mesh/src/aabb_normals.o: file not recognized: file format not recognized
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    Running setup.py install for psbody-mesh ... error
ERROR: Command errored out with exit status 1: /home/brandeea/anaconda3/envs/voca/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vzuvwcw1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vzuvwcw1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ou_ndsd0/install-record.txt --single-version-externally-managed --compile --install-headers /home/brandeea/anaconda3/envs/voca/include/python3.6m/psbody-mesh --boost-location=/usr/include/boost Check the logs for full command output.    
Exception information:
Traceback (most recent call last):
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 852, in install
    req_description=str(self.req),
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 406, in run
    pycompile=options.compile,
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 277, in runner
    spinner=spinner,
  File "/home/brandeea/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/brandeea/anaconda3/envs/voca/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vzuvwcw1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vzuvwcw1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ou_ndsd0/install-record.txt --single-version-externally-managed --compile --install-headers /home/brandeea/anaconda3/envs/voca/include/python3.6m/psbody-mesh --boost-location=/usr/include/boost Check the logs for full command output.

```
The python version in my environment is 3.6.8, the pip version is 20.2.4, gcc 10.2.0 and boost version 1.72.0-2.
Could you please help me out with this issue?

Thank you!

**Comment by cfanyyx** [comment]
Maybe you need update your gcc version, for example, update to 7.3.
