### ISSUE TITLE
ModuleNotFoundError: No module named 'psbody.smpl'

### ISSUE THREAD

**Issue by AmitSharma1127** [MPI-IS/mesh#60]
### To reproduce
*in **prep_data** directory*
``` 
python run.py 
```
### Output
```
correspondences.py  json_params  opendr  pip  run.py  sil_match.py  texture_extract.py  utils
Traceback (most recent call last):
  File "sil_match.py", line 19, in <module>
    from utils.smpl_paths import SmplPaths
  File "/home/local/AAPL/mgawali/pix2surf2/prep_data/utils/smpl_paths.py", line 5, in <module>
    from psbody.smpl import load_model
ModuleNotFoundError: No module named 'psbody.smpl'
/home/local/AAPL/mgawali/pix2surf2/assets/fmaps/pants.npy
Traceback (most recent call last):
  File "correspondences.py", line 86, in <module>
    main(args.mesh_file, args.sv_cords, args.side, args.size, args.fmap_location, args.bmap_location, args.cam_file, args.gar_type)
  File "correspondences.py", line 27, in main
    cam_data = pkl.load(open(cam_file, 'r'))
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "texture_extract.py", line 10, in <module>
    from utils.iso import Isomapper
  File "/home/local/AAPL/mgawali/pix2surf2/prep_data/utils/iso.py", line 7, in <module>
    from .renderer import OrthoTexturedRenderer, OrthoColoredRenderer
  File "/home/local/AAPL/mgawali/pix2surf2/prep_data/utils/renderer.py", line 9, in <module>
    from opendr.renderer import draw_edge_visibility, draw_boundary_images, draw_boundaryid_image
ImportError: cannot import name 'draw_edge_visibility'
```
### Conda list ouput
```
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
bottleneck                1.3.1            py36hdd07704_0
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.1.19            h06a4308_1
cairo                     1.14.12              h8948797_3
certifi                   2020.12.5        py36h06a4308_0
cffi                      1.14.0           py36h2e261b9_0
chumpy                    0.70                     pypi_0    pypi
cudatoolkit               10.0.130                      0
ffmpeg                    4.0                  hcdf2ecd_0
fontconfig                2.13.1               h6c09931_0
freeglut                  3.0.0                hf484d3e_5
freetype                  2.10.4               h5ab3b9f_0
glib                      2.63.1               h5a9c865_0
graphite2                 1.3.14               h23475e2_0
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.2               hba1933b_1
icu                       58.2                 he6710b0_3
intel-openmp              2020.2                      254
jasper                    2.0.14               h07fcdf6_1
jpeg                      9b                   h024ee3a_2
lcms2                     2.11                 h396b838_0
libedit                   3.1.20210216         h27cfd23_1
libffi                    3.2.1             hf484d3e_1007
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libglu                    9.0.0                hf484d3e_1
libopencv                 3.4.2                hb342d67_1
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.2.0                h3942068_0
libuuid                   1.0.3                h1bed415_2
libvpx                    1.7.0                h439df22_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
lz4-c                     1.9.3                h2531618_0
mkl                       2020.2                      256
mkl-service               2.3.0            py36he8ac12f_0
mkl_random                1.1.1            py36h0573a6f_0
ncurses                   6.2                  he6710b0_1
ninja                     1.10.2           py36hff7bd54_0
numpy                     1.14.2           py36hdbf6ddf_0
olefile                   0.46                     py36_0
opencv                    3.4.2            py36h6fd60c2_1
opendr                    0.73                     pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickle-mixin              1.0.2                    pypi_0    pypi
pillow                    6.2.1            py36h34e0f95_0
pip                       21.0.1           py36h06a4308_0
pixman                    0.40.0               h7b6447c_0
psbody-mesh               0.4                      pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2
py-opencv                 3.4.2            py36hb342d67_1
pycparser                 2.20                       py_2
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.9                h265db76_0
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.0.1           py3.6_cuda10.0.130_cudnn7.4.2_2    pytorch
readline                  7.0                  h7b6447c_5
scipy                     1.2.0            py36h7c811a0_0
setuptools                52.0.0           py36h06a4308_0
six                       1.15.0           py36h06a4308_0
sqlite                    3.33.0               h62c20be_0
tk                        8.6.10               hbc83047_0
torchvision               0.2.1                      py_2    pytorch
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0
```
### Additional Comments
Apart from changing compatibility from python 2.x to 3.x, such as changing `import cPickle as pkl` to `import pickle as pkl` I haven't done any other changes.

**Comment by jcpassy** [comment]
Hi @AmitSharma1127 ,
I think you are talking about other packages (`smpl`, `pix2surf2`) not `mesh`.
